[21-May-2024 19:34:54 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'162.241.61.154' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('proplsor-online...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:35:12 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'162.241.61.154' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('proplsor-online...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:35:12 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'162.241.61.154' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('proplsor-online...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:35:14 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'162.241.61.154' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('proplsor-online...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:35:16 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'162.241.61.154' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('proplsor-online...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:35:18 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'162.241.61.154' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('proplsor-online...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:35:20 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'162.241.61.154' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('proplsor-online...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:35:22 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'162.241.61.154' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('proplsor-online...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:35:24 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'162.241.61.154' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('proplsor-online...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:35:26 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'162.241.61.154' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('proplsor-online...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:35:28 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'162.241.61.154' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('proplsor-online...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:35:30 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'162.241.61.154' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('proplsor-online...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:35:32 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'162.241.61.154' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('proplsor-online...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:35:34 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'162.241.61.154' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('proplsor-online...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:35:36 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'162.241.61.154' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('proplsor-online...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:35:38 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'162.241.61.154' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('proplsor-online...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:35:40 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'162.241.61.154' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('proplsor-online...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:35:42 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'162.241.61.154' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('proplsor-online...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:35:44 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'162.241.61.154' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('proplsor-online...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:35:46 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'162.241.61.154' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('proplsor-online...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:35:48 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'162.241.61.154' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('proplsor-online...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:35:50 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'162.241.61.154' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('proplsor-online...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:35:52 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'162.241.61.154' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('proplsor-online...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:35:54 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'162.241.61.154' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('proplsor-online...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:35:56 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'162.241.61.154' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('proplsor-online...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:35:58 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'162.241.61.154' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('proplsor-online...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:36:00 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'162.241.61.154' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('proplsor-online...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:36:02 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'162.241.61.154' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('proplsor-online...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:36:04 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'162.241.61.154' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('proplsor-online...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:36:06 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'162.241.61.154' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('proplsor-online...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:36:08 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'162.241.61.154' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('proplsor-online...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:36:10 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'162.241.61.154' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('proplsor-online...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:36:12 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'162.241.61.154' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('proplsor-online...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:36:14 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'162.241.61.154' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('proplsor-online...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:36:27 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'162.241.61.154' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('proplsor-online...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:36:28 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'162.241.61.154' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('proplsor-online...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:36:30 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'162.241.61.154' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('proplsor-online...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:36:32 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'162.241.61.154' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('proplsor-online...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:36:34 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'162.241.61.154' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('proplsor-online...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:36:36 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'162.241.61.154' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('proplsor-online...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:36:38 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'162.241.61.154' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('proplsor-online...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:36:40 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'162.241.61.154' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('proplsor-online...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:36:42 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'162.241.61.154' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('proplsor-online...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:36:44 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'162.241.61.154' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('proplsor-online...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:36:46 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'162.241.61.154' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('proplsor-online...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:36:48 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'162.241.61.154' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('proplsor-online...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:36:50 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'162.241.61.154' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('proplsor-online...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:36:52 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'162.241.61.154' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('proplsor-online...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:36:54 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'162.241.61.154' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('proplsor-online...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:36:56 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'162.241.61.154' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('proplsor-online...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:36:58 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'162.241.61.154' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('proplsor-online...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:37:00 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'162.241.61.154' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('proplsor-online...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:37:02 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'162.241.61.154' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('proplsor-online...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:37:04 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'162.241.61.154' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('proplsor-online...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:37:06 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'162.241.61.154' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('proplsor-online...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:37:08 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'162.241.61.154' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('proplsor-online...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:37:10 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'162.241.61.154' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('proplsor-online...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:37:12 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'162.241.61.154' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('proplsor-online...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:37:14 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'162.241.61.154' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('proplsor-online...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:37:16 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'162.241.61.154' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('proplsor-online...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:37:18 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'162.241.61.154' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('proplsor-online...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:37:20 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'162.241.61.154' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('proplsor-online...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:37:22 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'162.241.61.154' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('proplsor-online...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:37:24 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'162.241.61.154' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('proplsor-online...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:37:26 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'162.241.61.154' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('proplsor-online...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:37:28 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'nspro15.hostgator.co' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('nspro15.hostgat...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:37:30 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'nspro15.hostgator.co' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('nspro15.hostgat...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:37:32 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'nspro15.hostgator.co' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('nspro15.hostgat...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:37:34 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'nspro15.hostgator.co' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('nspro15.hostgat...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:37:36 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'nspro15.hostgator.co' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('nspro15.hostgat...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:37:38 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'nspro15.hostgator.co' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('nspro15.hostgat...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:37:40 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'nspro15.hostgator.co' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('nspro15.hostgat...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:37:42 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'nspro15.hostgator.co' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('nspro15.hostgat...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:37:44 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'nspro15.hostgator.co' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('nspro15.hostgat...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:37:46 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'nspro15.hostgator.co' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('nspro15.hostgat...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:37:48 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'nspro15.hostgator.co' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('nspro15.hostgat...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:37:50 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'nspro15.hostgator.co' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('nspro15.hostgat...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:37:52 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'nspro15.hostgator.co' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('nspro15.hostgat...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:37:54 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'nspro15.hostgator.co' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('nspro15.hostgat...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:37:56 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'nspro15.hostgator.co' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('nspro15.hostgat...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:37:58 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'nspro15.hostgator.co' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('nspro15.hostgat...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:38:00 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'nspro15.hostgator.co' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('nspro15.hostgat...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:38:02 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'nspro15.hostgator.co' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('nspro15.hostgat...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:38:04 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'nspro15.hostgator.co' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('nspro15.hostgat...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:38:06 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'nspro15.hostgator.co' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('nspro15.hostgat...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:38:08 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'nspro15.hostgator.co' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('nspro15.hostgat...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:38:10 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'nspro15.hostgator.co' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('nspro15.hostgat...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:38:12 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'nspro15.hostgator.co' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('nspro15.hostgat...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:38:14 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'nspro15.hostgator.co' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('nspro15.hostgat...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:38:16 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'nspro15.hostgator.co' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('nspro15.hostgat...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:38:18 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'nspro15.hostgator.co' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('nspro15.hostgat...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:38:20 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'nspro15.hostgator.co' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('nspro15.hostgat...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:38:22 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'nspro15.hostgator.co' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('nspro15.hostgat...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:38:24 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'nspro15.hostgator.co' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('nspro15.hostgat...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:38:26 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'nspro15.hostgator.co' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('nspro15.hostgat...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:38:28 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'nspro15.hostgator.co' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('nspro15.hostgat...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:38:30 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'nspro15.hostgator.co' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('nspro15.hostgat...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:38:32 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'nspro15.hostgator.co' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('nspro15.hostgat...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:38:34 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'nspro15.hostgator.co' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('nspro15.hostgat...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:38:36 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'nspro15.hostgator.co' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('nspro15.hostgat...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:38:38 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'nspro15.hostgator.co' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('nspro15.hostgat...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:38:40 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'nspro15.hostgator.co' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('nspro15.hostgat...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:39:33 America/Bogota] PHP Warning:  mysqli_connect(): php_network_getaddresses: getaddrinfo for sh-pro14.co failed: Name or service not known in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:39:33 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: php_network_getaddresses: getaddrinfo for sh-pro14.co failed: Name or service not known in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('sh-pro14.co', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:40:33 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'sh-pro14.hostgator.co' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('shared18.hostga...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:41:33 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'sh-pro14.hostgator.co' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('shared18.hostga...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:42:33 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'sh-pro14.hostgator.co' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('shared18.hostga...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:43:33 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'sh-pro14.hostgator.co' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('shared18.hostga...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:44:33 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'sh-pro14.hostgator.co' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('shared18.hostga...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:45:33 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'sh-pro14.hostgator.co' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('shared18.hostga...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
[21-May-2024 19:46:33 America/Bogota] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'proplso1_inelda23'@'sh-pro14.hostgator.co' (using password: YES) in /home2/proplso1/public_html/prueba/lib/conexion.php:11
Stack trace:
#0 /home2/proplso1/public_html/prueba/lib/conexion.php(11): mysqli_connect('shared18.hostga...', 'proplso1_inelda...', Object(SensitiveParameterValue), 'proplso1_inelda...')
#1 /home2/proplso1/public_html/prueba/lib/funciones.php(95): conectar()
#2 /home2/proplso1/public_html/prueba/process/casos.php(3): cargar_casos()
#3 {main}
  thrown in /home2/proplso1/public_html/prueba/lib/conexion.php on line 11
